force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/Airline_Trip_Emissions_Estimate__c.object-meta.xml
<CustomObject>
    <description>Stores the flight carbon emissions data for an airline trip involving one or more legs.</description>
    <label>Airline Trip Emissions Estimate</label>
    <nameField>
        <displayFormat>ATEE-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airline Trip Emissions Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/Final_Destination_Airport__c.field-meta.xml
<CustomField>
    <fullName>Final_Destination_Airport__c</fullName>
    <description>Represents the final airport in a one-way trip or, for a return trip, the destination airport prior to the return.</description>
    <label>Final Destination Airport</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IATA_Airport_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/Number_of_Passengers__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Passengers__c</fullName>
    <description>Indicates the number of passengers taking the trip.</description>
    <label>Number of Passengers</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/Origination_Airport__c.field-meta.xml
<CustomField>
    <fullName>Origination_Airport__c</fullName>
    <description>Contains the 3-letter airport code of the originatin (first departure) airport.</description>
    <label>Origination Airport</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IATA_Airport_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AirlineTripEmissionsTriggerHandler.cls
//
// April 2023
// Build Together Integration 4
// Carbon Interface API - Airline Emissions
// code by Neil Hohmann
// 

public with sharing class AirlineTripEmissionsTriggerHandler {
    public static List<Airline_Trip_Emissions_Estimate__c> ATEEsToProcess = new List<Airline_Trip_Emissions_Estimate__c>();
    public static List<String> airportCodes = new List<String>();

    public static void beforeInsert(List<Airline_Trip_Emissions_Estimate__c> newATEEs){
        for(Airline_Trip_Emissions_Estimate__c newATEE : newATEEs){
            if(String.isEmpty(newATEE.Transaction_ID__c) && newATEE.Request_Date_Time__c == null){
                ATEEsToProcess.add(newATEE);
            }
        }
        if (ATEEsToProcess.size() > 0){
            // Here I'm not passing ATEEsToProcess since I assume it will already be accessible in prepareCallout()
            for(Airline_Trip_Emissions_Estimate__c nextATEE : ATEEsToProcess){
                defineAirports(nextATEE);
                createWrapper(nextATEE);
            }
        }
    }

    public static void defineAirports(Airline_Trip_Emissions_Estimate__c nextATEE){
        airportCodes.add(String.valueOf(nextATEE.Origination_Airport__c));
        if (nextATEE.Layover_Airport__c != null){          
            airportCodes.add(String.valueOf(nextATEE.Layover_Airport__c));   
        }
        airportCodes.add(String.valueOf(nextATEE.Final_Destination_Airport__c));
        System.debug('airportCodes: ' + airportCodes);
    }


    public static void createWrapper(Airline_Trip_Emissions_Estimate__c nextATEE){
        CarbonBodyWrapper wrapper = new CarbonBodyWrapper();
        wrapper.type          = 'flight';
        wrapper.passengers    = nextATEE.Number_of_Passengers__c.intValue();
        wrapper.legs          = CarbonRequestSender.processLegs(airportCodes, nextATEE.Round_Trip__c);
        wrapper.distance_unit = 'mi';
        System.debug('wrapper: ' + wrapper);
        System.debug('Legs: ' + CarbonRequestSender.displayLegs);
    }
}