force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/Airline_Trip_Emissions_Estimate__c.object-meta.xml
<CustomObject>
    <description>Stores the flight carbon emissions data for an airline trip involving one or more legs.</description>
    <label>Airline Trip Emissions Estimate</label>
    <nameField>
        <displayFormat>ATEE-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airline Trip Emissions Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/CO2e_kg__c.field-meta.xml
<CustomField>
    <fullName>CO2e_kg__c</fullName>
    <description>Carbon dioxide equivalent (CO2e) in kilograms (kg).</description>
    <label>CO2e kg</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/CO2e_lb__c.field-meta.xml
<CustomField>
    <fullName>CO2e_lb__c</fullName>
    <description>Carbon dioxide equivalent (CO2e) in pounds (lb).</description>
    <label>CO2e lb</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/CO2e_mt__c.field-meta.xml
<CustomField>
    <fullName>CO2e_mt__c</fullName>
    <description>Carbon dioxide equivalent (CO2e) in metric tons (mt).</description>
    <label>CO2e mt</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/Final_Destination_Airport__c.field-meta.xml
<CustomField>
    <fullName>Final_Destination_Airport__c</fullName>
    <description>Represents the final airport in a one-way trip or, for a return trip, the destination airport prior to the return.</description>
    <label>Final Destination Airport</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IATA_Airport_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/Legs__c.field-meta.xml
<CustomField>
    <fullName>Legs__c</fullName>
    <description>Lists individual legs of the trip.</description>
    <label>Legs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/Number_of_Legs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Legs__c</fullName>
    <description>Indicates the total number of legs for the trip.</description>
    <label>Number of Legs</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/Number_of_Passengers__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Passengers__c</fullName>
    <description>Indicates the number of passengers taking the trip.</description>
    <label>Number of Passengers</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airline_Trip_Emissions_Estimate__c/fields/Origination_Airport__c.field-meta.xml
<CustomField>
    <fullName>Origination_Airport__c</fullName>
    <description>Contains the 3-letter airport code of the originatin (first departure) airport.</description>
    <label>Origination Airport</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IATA_Airport_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AirlineEmissionsTrip.cls
//
// April 2023
// Build Together Integration 4
// Carbon Interface API - Airline Emissions
// Team 2: team-EMEA
// 


public class AirlineEmissionsTrip {
    public static String idToReturnToFlow;

    public static void createAteeObject(List<String> airportCodes, String legsToDisplay, Boolean roundtrip, CarbonResponseWrapper response) {
        Airline_Trip_Emissions_Estimate__c currentATEE = new Airline_Trip_Emissions_Estimate__c();
        
        String originationAirport      = airportCodes.get(0);
        String finalDestinationAirport = airportCodes.get(airportCodes.size()-1);

        // Create Flight Details fields >> all captured in Flow
        currentATEE.Number_of_Legs__c            = response.data.attributes.legs.size();
        currentATEE.Legs__c                      = legsToDisplay;
        currentATEE.Origination_Airport__c       = originationAirport;
        currentATEE.Final_Destination_Airport__c = finalDestinationAirport;
        currentATEE.Number_of_Passengers__c      = response.data.attributes.passengers;
        currentATEE.Round_Trip__c                = roundtrip;
        currentATEE.Non_Stop_Flight__c           = TRUE;


        if (airportCodes.size() == 3){
            String layoverAirport = airportCodes.get(1);
            // Set Layover Airport and uncheck Non-Stop Flight
            currentATEE.Layover_Airport__c = layoverAirport;
            currentATEE.Non_Stop_Flight__c = FALSE;
        }

        // Create Carbon Interface Emissions Data fields
        currentATEE.Request_Date_Time__c = Datetime.valueOf(response.data.attributes.estimated_at.replace('T',' ')).addHours(2);
        currentATEE.Transaction_ID__c    = response.data.id;
        currentATEE.Flight_Distance__c   = response.data.attributes.distance_value;
        currentATEE.Distance_Unit__c     = response.data.attributes.distance_unit;
        currentATEE.CO2e_lb__c           = response.data.attributes.carbon_lb;
        currentATEE.CO2e_kg__c           = response.data.attributes.carbon_kg;
        currentATEE.CO2e_mt__c           = response.data.attributes.carbon_mt;

        Insert currentATEE;

        idToReturnToFlow = currentATEE.Id;
    }
}